New build process
pusher/prom-rule-reloader pull request #5
Opened 2019-04-09 09:44 UTC by gargath

This adds a Makefile and configure script along with common build targets.
These replace the old Wercker build and prepare the repo for Prow.

2019-04-09 09:50 UTC, mthssdrbrg requested changes
Looks good in general! Got a few questions and spotted a typo.

2019-04-09 09:50 UTC, mthssdrbrg commented on Dockerfile
> +FROM golang:1.10.3 AS builder
Any reason for not going to v1.12?

2019-04-09 09:50 UTC, mthssdrbrg commented on Dockerfile
> +FROM alpine:3.8
Similar to my previous question, any reason for not going to 3.9? :)

2019-04-09 09:50 UTC, mthssdrbrg commented on Makefile
> +	@ echo "$(GREEN)Puling dependencies$(NC)"
`s/Puling/Pulling`

2019-04-09 09:50 UTC, mthssdrbrg commented on Makefile
> +	CGO_ENABLED=0 $(GO) build -o $(BINARY) -ldflags="-X main.VERSION=${VERSION}" github.com/pusher/prom-rule-reloader/cmd
There's no `VERSION` variable specified in the `main` package, so we should either add that (could be added in `main.go`) or remove `-ldflags`.

2019-04-09 09:50 UTC, mthssdrbrg commented on Makefile
> +	CGO_ENABLED=0 $(GO) build -o $(BINARY) -ldflags="-X main.VERSION=${VERSION}" github.com/pusher/prom-rule-reloader/cmd
Also just noticed that the Dockerfile doesn't include `-ldflags` when building the binary.

2019-04-09 12:33 UTC, gargath commented on Dockerfile
> +FROM golang:1.10.3 AS builder
Copied what faros is using, I think. Happy to try 1.12

2019-04-09 12:34 UTC, gargath commented on Makefile
> +	CGO_ENABLED=0 $(GO) build -o $(BINARY) -ldflags="-X main.VERSION=${VERSION}" github.com/pusher/prom-rule-reloader/cmd
This is fixed in #6. I decided to make that a separate PR in the end. If we're merging them together I don't think there's a need to remove it here, wdyt?

2019-04-09 14:19 UTC, gargath commented
/build docker

2019-04-09 15:37 UTC, gargath commented
/build docker

2019-04-10 09:34 UTC, mthssdrbrg commented on Makefile
> +	CGO_ENABLED=0 $(GO) build -o $(BINARY) -ldflags="-X main.VERSION=${VERSION}" github.com/pusher/prom-rule-reloader/cmd
I personally prefer that :)

2019-04-10 10:37 UTC, mthssdrbrg approved these changes
LGTM

2019-04-10 10:39 UTC, JoelSpeed commented on Makefile
> +	  --enable=vet \
`golangci-lint` doesn't actually support `vet` and `vetshadow` but merges them into `govet` I believe.

It also ignores a bunch of lint rules that we have been using previously, see changes in https://github.com/pusher/faros/pull/125/files

2019-04-10 10:39 UTC, JoelSpeed commented on Makefile
> +docker-clean:
Useful, hadn't thought about doing something like this before

2019-04-10 11:41 UTC, gargath commented on Makefile
> +	  --enable=vet \
I'll update the list. Thanks :)

2019-04-11 10:14 UTC, JoelSpeed approved these changes

2019-04-11 10:20 UTC, merged